name: check
on: [push]

jobs:
  check:
    name: make check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: pipenv3 sync --dev
      - name: run unit and functional tests
        run: make check
